### ISSUE TITLE
Adding warning lines to IGNORED_WARNINGS don't always resolve the issue

### ISSUE THREAD

**Issue by BeckerHanne** [DCMLab/dcml_corpus_workflow#33]
I experienced this on 2 PRs in the couperin_concert repo so far: when adding clearly correct labels to the IGNORED_WARNINGS file and saving as usual, running the local ms3 still gives those very same warnings. I tried deleting everything, and entering it again, but the problem persists.

I'm currently on c08n02_ritournele

**Comment by johentsch** [comment]
Thanks for reporting. Fixed on `ms3@corpus_structure` (currently active workflow) and in the next release.
