### ISSUE TITLE
ERROR MC27 not found for c14n02_allemande in couperin_concerts

### ISSUE THREAD

**Issue by BeckerHanne** [DCMLab/dcml_corpus_workflow#34]
The local ms3 test is passing after adding incomplete measures to the IGNORED_WARNINGS file.

However: I am getting an ERROR message as follows:
ERROR    ms3.Parse.couperin_concerts.c14n02_allemande 
        MC 27 not found.

The original score does not seem to have 27 measures either, so I am puzzled with this one. PR#104 in couperin_concerts

**Comment by johentsch** [comment]
https://github.com/DCMLab/couperin_concerts/pull/104#issuecomment-1637612475
